spring:
  datasource:
    driver-class-name: "org.testcontainers.jdbc.ContainerDatabaseDriver"
    url: "jdbc:tc:postgresql:10:///testDb"
    username: "test"
    password: "test"
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        order_inserts: true
        jdbc:
          batch_size: 100